### ISSUE TITLE
verify  bench test buttons work in FOME-fw

### ISSUE THREAD

**Issue by mi-hol** [FOME-Tech/wiki#100]
https://github.com/rusefi/rusefi/issues/5327 mentions not working bench test buttons listed below and provides fixes:

- [x] main relay
- [x] pump relay
- [x]  HPFP valve

Is FOME firmware affected too?
in case it is, backporting the fixes seems are requirement for V1

**Comment by mi-hol** [comment]
@OrchardPerformance oops I created issue in wrong repo, could you please move to fomw-fw?

**Comment by OrchardPerformance** [comment]
Will do.

I used main relay test with a scope to check rover boards not more than a week ago. 

I think fome release is OK.
