### ISSUE TITLE
GH workflows in forked wiki repo can not succeed by design 

### ISSUE THREAD

**Issue by mi-hol** [FOME-Tech/wiki#110]
All forked workflows will fail "Deploy" job because they can not (and should not!) deploy to official wiki hosted on cloudflare

Solution:

check in workflow for "forked repos" and skip that step

**Comment by mi-hol** [comment]
I guess a check for user would fix the issue, unfortunately I'm not familiar with the proper syntax to create a PR

In seem to remember a similar issue in RE wiki and the fix seemed to be adding an "if:" condition like below
`jobs:
  sync:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'actions-user' }}`

**Comment by karniv00l** [comment]
@mi-hol can you please check now?

**Comment by mi-hol** [comment]
found below after I synced my fork. Guess the full story will become visible tomorrow 

![image](https://github.com/FOME-Tech/wiki/assets/22799428/7f3dfb46-515e-414c-ae82-d239685497cc)

Strangely I got below email
![image](https://github.com/FOME-Tech/wiki/assets/22799428/5a846e04-8a63-4f1e-b3e9-ff5088ae1b09)

**Comment by mi-hol** [comment]
Is this error epected?
![image](https://github.com/FOME-Tech/wiki/assets/22799428/fbd960e5-d053-4384-9b92-128716efed4f)

**Comment by karniv00l** [comment]
I think your fork looks fine now:

<img width="937" alt="Screenshot 2023-07-02 at 09 29 27" src="https://github.com/FOME-Tech/wiki/assets/3144291/6a97bf05-2c52-4bb2-81c5-4572ccfbd468">

cancelation reason:

<img width="723" alt="Screenshot 2023-07-02 at 09 31 11" src="https://github.com/FOME-Tech/wiki/assets/3144291/ca1f8fa6-a456-4c9c-9e30-228cf01792df">

**Comment by karniv00l** [comment]
Also, preview workflow is no more: https://github.com/FOME-Tech/wiki/pull/116
