### ISSUE TITLE
Proposal RfC: improve readability of wiki (online and pdf) by using "light" background on images

### ISSUE THREAD

**Issue by mi-hol** [FOME-Tech/wiki#120]
Issue:

Currently most images of screens are captured with a "dark" background.
From my view this has the following drawbacks:

1. low contrast causes issues with readability
   -   red or other color used for highlighting certain aspects of image is hard (if at all) to notice

3. a printed pdf is an "ink/toner killer"

Solution proposal:

- Capture screenshots always with "light" background setting
- add above statement as a rule in "quick guide for writers"
- if possible add a "lint" type validation for images to enforce this rule automatically

@FOME-Team
May I ask for your comments please?

**Comment by OrchardPerformance** [comment]
While I agree to some extent (mostly on the practicalities of printing etc) I think this may be premature optimization. 
A lot of apps either take the windows setting and set themselves into dark mode or will need the uses to change the colours around to achieve a light mode. 
At this point I would rather not ask people to switch their colour schemes about to take screen shots and that may be enough to stop them contributing. 

When we have all the content we need populated into pages then it may be time to look at dark/light for screen shots, until that point I think we should just accept what ever people are willing to provide. 
IMO a sub-optimal screen shot is better than no screen shot at all.

**Comment by OrchardPerformance** [comment]
Related but wanted to separate the points :- I would really urge people not to print the wiki, it's online in both mobile and desktop versions, it's downloadable as a PDF if internet is not available where yo work on the car.
Please put it on your tuning laptop, mobile phone, tablet, whatever and not waste paper and ink.
Perhaps this needs a thing added on the intro page? 
(insert hypocrisy of someone who build race cars caring about waste and the environment. :) )

**Comment by mi-hol** [comment]
> At this point I would rather not ask people to switch their colour schemes about to take screen shots and that may be enough to stop them contributing.

ok, get the point. How about making a recommendation instead of a hard rule?
Or in other words, are you ok to switch the colour schemes  to take screen shots?

**Comment by mi-hol** [comment]
BTW: I seem to have expressed the rules from BDA guidelines in slightly different words. there is phrased as:

- Use sufficient contrast levels between background and text.
- Use dark coloured text on a light (not white) background.

**Comment by mi-hol** [comment]
> Please put it on your tuning laptop, mobile phone, tablet, whatever and not waste paper and ink.

Even there a dark picture will be hard (if at all) to read as BDA Guidelines mention

**Comment by mi-hol** [comment]
closing due to lack of interest
