### ISSUE TITLE
Marketing .zip file links are broken

### ISSUE THREAD

**Issue by nmschulte** [FOME-Tech/wiki#269]
https://github.com/FOME-Tech/wiki/blob/4cc7533f389980a73a552c58ce90e05eab8b9400/docs/100-Brand-and-Marketing.md?plain=1#L15

For w/e reason, Docusaurus is putting a `files/` member in the URL linking to the `.zip` files on this page, leading to broken links.

**Comment by karniv00l** [comment]
I think the issue is with trailing slash: https://github.com/facebook/docusaurus/issues/6282

**Comment by nmschulte** [comment]
Oh, yep!  I didn't even notice -- nice find.
