### ISSUE TITLE
wiki gaps for release or something

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [FOME-Tech/wiki#64]
karniv00l
[3:27 AM](https://chat.fome.tech/fome/pl/aig7aqwrdtd3tfc6q8pzgc8qpy)

Regarding launch: 

- [x] we're missing wiki home / index - https://wiki.fome.tech/ (https://github.com/FOME-Tech/wiki/commit/8c4ab39b2095cb1dd10c098c71141d7c1876c88e)
- [x] site is blocked against crawlers (https://github.com/FOME-Tech/wiki/pull/65)
- [x] #68
- [x]  we don't have a search functionality - we could add Algolia (https://docusaurus.io/docs/search) once the repo is open sourced (https://github.com/FOME-Tech/wiki/commit/1ba1d6b9e460c7c7970f4bdc34d0f408c93e427a)

**Comment by mi-hol** [comment]
https://medium.com/geekculture/serverless-e-book-web-book-using-docusaurus-v2-github-pages-actions-and-pdf-tools-4fef54847b85 describes a more simple solution copied below.

I've yet to test it but would create a PR if it works
Would that be good enough?

`name: 'continous deployment'

on:
  push:
    branches:
      - master

jobs:
  generate_webbook:
    # ...

  generate_ebook:
    name: 'generate ebook'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install prince
      run: |
        curl https://www.princexml.com/download/prince-14.2-linux-generic-x86_64.tar.gz -O
        tar zxf prince-14.2-linux-generic-x86_64.tar.gz
        cd prince-14.2-linux-generic-x86_64
        yes "" | sudo ./install.sh
    - name: build pdf
      run: npx docusaurus-prince-pdf -u https://my-book.novalagung.com/intro
    - name: publish ebook
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PAT }}
        publish_dir: ./pdf`

**Comment by karniv00l** [comment]
All done
